spring:
  banner:
    location: remember_logo.txt
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/java_study_code?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: zjh20040724
server:
  port: 8888