spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/exercitation_experience_api?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: zjh20040724
  mail: # 邮箱配置
    host: smtp.qq.com
    port: 465
    username: zsjt.remember@qq.com # 发件邮箱
    password: imznacucidqndfje  # 邮箱授权码
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            enable: true
            protocols: TLSv1.2
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
# 控制台日志输出
logging:
  level:
    com:
      remember:
        mapper: debug
        service: info
        controller: info



